### ISSUE TITLE
Bug with the login page in deployment

### ISSUE THREAD

**Issue by Pelayo-Reguera** [Arquisoft/lomap_en3a#106]
After logging in Inrupt, it seems that it is not detected by the SolidSessionManager, which relies on Inrupt library functions. However, when executing in local, no problem arises.

**Comment by UO283428** [comment]
Pablo has commented that we have to do is to debug what the app is doing once we have logged in.
Also, commented the usage of hooks or UseEffect on the component in order not to lose the IsLogin variable. As if we use state it will always be false.

**Comment by uo282892** [comment]
I am investigating on the use of CORS in webapp. However, it is difficult as all the examples are based on RESTAPI and we do not have the same structure.

**Comment by uo282892** [comment]
@pglez82 The application was deployed yesterday on Github Pages and it works fine. Therefore, I think we can assume that the key point is the use of HTTPS. So, the following paths can be taken:

- Configure the Github Actions (yml file) to automate the deployment with Github Pages.
- Manage to enable HTTPS with Azure.

**Comment by pglez82** [comment]
Yes, I am pretty sure this is the issue.

My recommendation is to use [letscript](https://letsencrypt.org/es/getting-started/).

If you need a custom domain you can check any free DNS service.

Pablo

**Comment by uo282892** [comment]
@pglez82 I have been trying your proposal. I will try to explain what I did as clear as possible.

# Free DNS Service

Finding this was so troublesome for me. There are many fishy websites that are scams, and others force you to pay a plan before letting you access to the promised free domain. Among the several alternatives I checked, I an currently with ClouDNS. It does not let you create a free domain per se, but a free dns zone with a fixed name (cloudns.XX). These are my current settings (note the A record with the ip of the Azure vm):

![imagen](https://user-images.githubusercontent.com/98897888/234031008-20ae4a02-ae11-4bba-a33e-7d898b248a9b.png)


# Letsencrypt (Certbot)

From I could understand, the recommended way to use Letsencrypt is by means of Certbot. It has its own website where you specify what you are running and where, and custom instructions appear. The machine is pretty clear, since I created a Ubuntu 20.04 VM. However,  I am not sure what I should put on the first combobox, because if you put "Software" no instruction appear. I guess I could install Nginx on the VM and then follow the instructions, but I put "Other" and a set of them appeared so I followed them on the vm

![imagen](https://user-images.githubusercontent.com/98897888/234032501-eb28c234-a1fc-4ba5-9400-9c297b8e82b1.png)

In the VM, I arrived until this point:

![imagen](https://user-images.githubusercontent.com/98897888/234032837-4cc0339f-31f3-4e67-8dcd-15efc3e646aa.png)

I do not really know if the problem is that I do not have really a domain, or what. Please, if you know what is happening or you have any suggestion about how you get a free domain (to be sure we have one, maybe I did something totally different) or how to use Letsencrypt (in case I was applying something that does not work for our specifc situation), please let us know.

**Comment by pglez82** [comment]
You need to open the ports in the azure machine. The only thing that you are doing is, verifying that the machine in this domain is actually yours. Certbot is trying to access you machine but it is not able to. Open ports 80 a 443 in the machine, allow access to them to any IP and repeat the instructions.

**Comment by pglez82** [comment]
Remember that you need to configure your webserver to use the certificates. It wont work automatically.

**Comment by pglez82** [comment]
Ok. Some considerations:

1) `sudo certbot certonly --standalone` launchs a temporal webserver to which they connect to verify that you own the machine. This means, after verifying the certificate, nothing will be listening in port 80. So the behaviour that you are getting I think is expected.

2) Are you running your react application in port 443? That is the default port for a https application. If you are running it in port 3000 I do not think it is going to work. Here I post some code that I use to run an https react application. I place it in a file server.js:

```javascript
var fs = require('fs');
var http = require('http');
var https = require('https');
const express = require('express');
var expressStaticGzip = require('express-static-gzip');
const path = require('path');

//Load certificates
var privateKey  = fs.readFileSync('claves/privkey.pem');
var certificate = fs.readFileSync('claves/fullchain.pem');
var credentials = {key: privateKey, cert: certificate};

var app = express();

//This will make sure that we will serve everything through https
app.all('*', function(req, res, next){
    if (req.secure) {
      return next();
    }  
    res.redirect('https://'+req.hostname + req.url);
  });

//Base path of our application. We serve first the brotli version (compression).
app.use('/', expressStaticGzip('build', {
    enableBrotli: true,
    orderPreference: ['br']
}));

//For react routes to work, fallback to index.html
app.get('*', (req, res) => {                       
    res.sendFile(path.resolve(__dirname, 'build', 'index.html'));                               
  });

var httpsServer = https.createServer(credentials, app);
httpsServer.listen(443);
```
As you can see I am creating an express server (suitable for production, not like `npm start`)  and redirecting all traffic to https. 

Obviously, for this work using docker, you need to have the certificates in the same directory as the app. My dockerfile is very simple, it looks like:

```docker
FROM node:18-alpine
COPY . /app
WORKDIR /app
RUN npm install --only=prod
RUN npm run build
CMD node server.js
```

**Comment by pglez82** [comment]
Good job! I will not worry about that.

Pablo
